#!/usr/bin/env python

# Hyperlapse Trigger Injector Script
# Script Version
ver = 1.3
# By Robbie Ferguson // The Bald Nerd
# Category5 TV Network
# View the series: https://cat5.tv/3dprinting

import sys
import re

# NOTE:
# Some lines are commented which may cause issues. I've left them here for experimentation purposes, but commented out so they're not used in production.

# I recommend you leave this header in your gcode output so you can later refer to it and know which version of my script you used
output = "; Hyperlapse Trigger v" + str(ver) + " by Robbie Ferguson - https://cat5.tv/3dprinting\n"
count = 0
try:
  lr = sys.argv[2].strip()
  left = ['l','left']
  right = ['r','right']
  if lr.lower() in left:
    lr = "l"
  if lr.lower() in right:
    lr = "r"
  print lr
except IndexError:
  lr = "l"
  pass

# Some possible trigger points are:
# ";TYPE:" - Take several shots throughout each layer, during the progress - Takes too long and probably causes stringing.
# ";TIME_ELAPSED:" - After each layer, including one extra at the end.
# ";LAYER:" - Before every layer, plus at the end. This is the default but kinda boring on small prints.
# ";MESH:" - Before every mesh.

#trigger_point=";TYPE:"
#trigger_point=";TIME_ELAPSED:"
trigger_point=";LAYER:"
#trigger_point=";MESH:"

# Setup the trigger code
trigger = ""
trigger += "G91; Relative movement\n"
trigger += "G1 F3000 Z2; Raise Z\n"
trigger += "G90; Absolute movement\n"
if lr == "l":
  trigger += "G1 F9000 X12 Y215; Quick move to switch on left\n"
  trigger += "G1 F1000 X0; Tap the button\n"
if lr == "r":
  trigger += "G1 F9000 X190 Y210; Quick move to switch on right\n"
  trigger += "G1 F1000 X197; Tap the button\n"
trigger += "G4 P50; Smile!\n" # Increase or decrease (in milliseconds) to change shutter hold time / increase or decrease shutter / exposure time
if lr == "l":
  trigger += "G1 F9000 X12; Back up\n"
if lr == "r":
  output += "G1 F9000 X190; Back up\n"
trigger += "G4 P500; Wait half a sec\n"
trigger += "G91; Relative movement\n"
trigger += "G1 F3000 Z-2; Lower Z\n"

try:
  with open(sys.argv[1],'r') as gcode:
    x = ""
    y = ""
    z = ""
    for line in gcode:
      line = line.strip()
      if ';HYPERLAPSE TRIGGER' in line:
        sys.exit(sys.argv[1] + " already has trigger code.")
      coord = re.findall(r'[XYZ].?\d+.\d+',line)
      if coord:
        if 'X' in coord[0]:
          x = coord[0]
        if 'Y' in coord[0]:
          y = coord[0]
        if 'Z' in coord[0]:
          z = coord[0]
        try:
          if 'X' in coord[1]:
            x = coord[1]
          if 'Y' in coord[1]:
            y = coord[1]
          if 'Z' in coord[1]:
            z = coord[1]
        except IndexError:
           pass
        try:
          if 'X' in coord[2]:
            x = coord[2]
          if 'Y' in coord[2]:
            y = coord[2]
          if 'Z' in coord[2]:
            z = coord[2]
        except IndexError:
           pass
        lastcoord = x + " " + y
      if trigger_point in line:
        output += ";HYPERLAPSE TRIGGER\n"
        count += 1
        output += "M117 Frame " + str(count) + "\n"
        output += "G91; Relative movement\n"
        # Note the retraction distance is set for bowden feed.
        # For direct, use 1-2mm and change the return movement below.
        output += "G1 E-7 F4800; Retract filament\n"

        output += trigger

        output += "G90; Absolute movement\n"
        try:
          output += "G0 " + lastcoord + " F9000; Return to print\n"
        except NameError:
          pass
#        try:
#          output += "G0 " + z + " F3000; Lower Z to print\n"
#        except NameError:
#          pass
#        output += "G91; Relative movement\n"
        # Remember, this is relative. Absolute value will very quickly override.
        # But we'll push out more than we retracted very quickly to prime the extruder.
#        output += "G1 E6 F4800; Return filament\n"
#        output += "G90; Absolute movement\n"
      output += line + "\n"

    # Add frame count
    finaloutput = ""
    count2 = 0
    fps = 30 # Frames per second of resulting hyperlapse
    totalSeconds = int(round(count/fps))
    for line in output.splitlines():
      line = line.strip()
      finaloutput += line
      if 'M117 Frame' in line:
        count2 += 1
        currentSeconds = int(round(count2/fps))
        finaloutput += "/" + str(count) + " (" + str(currentSeconds) + "s/"+ str(totalSeconds) + "s " + str(fps) + "FPS); Output Hyperlapse Progress to Screen"
      finaloutput += "\n"

    # Output the gcode and take a picture at the end of the final product
    print finaloutput + trigger

except IndexError:
  sys.exit("Usage: " + sys.argv[0] + " myfile.gcode [l|r]\n       Where myfile.gcode is the input file. l[eft] or r[ight] are the location of your switch. l is default.\n\nNote: Can pipe the output to a new file.")
except IOError:
  sys.exit(sys.argv[1] + " not found.")
